<?php 
/**
 * Reports upload view page.
 *
 * PHP version 5
 * LICENSE: This source file is subject to LGPL license 
 * that is available through the world-wide-web at the following URI:
 * http://www.gnu.org/copyleft/lesser.html
 * @author     Ushahidi Team <team@ushahidi.com> 
 * @package    Ushahidi - http://source.ushahididev.com
 * @module     API Controller
 * @copyright  Ushahidi - http://www.ushahidi.com
 * @license    http://www.gnu.org/copyleft/lesser.html GNU Lesser General Public License (LGPL) 
 */
include "application/config/mysql_connect.php";
?>

<div class="bg">
	<h2>
		<?php admin::reports_subtabs("group"); ?>
	</h2>
    <?php
    	$strSqlCommand  = "DELETE FROM `Group` WHERE `id`=0";
		mysql_query($strSqlCommand);
	?>
    
    <style type="text/css">
.css_btn_class {
	font-size:12px;
	font-family:Arial;
	font-weight:normal;
	/*-moz-border-radius:0px;
	-webkit-border-radius:0px;
	border-radius:0px;*/
	border:1px solid lightgray;
	padding:9px 9px;
	text-decoration:none;
	/*background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #bddbfa), color-stop(100%, #80b5ea) );
	background:-moz-linear-gradient( center top, #bddbfa 5%, #80b5ea 100% );
	background:-ms-linear-gradient( top, #bddbfa 5%, #80b5ea 100% );*/
	/*filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#bddbfa', endColorstr='#80b5ea');*/
	background-color:#EBEBFF;
	color:dimgray;
	/*display:inline-block;*/
}
/*
.css_btn_class:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(5%, #80b5ea), color-stop(100%, #bddbfa) );
	background:-moz-linear-gradient( center top, #80b5ea 5%, #bddbfa 100% );
	background:-ms-linear-gradient( top, #80b5ea 5%, #bddbfa 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#80b5ea', endColorstr='#bddbfa');
	background-color:#80b5ea;
}
.css_btn_class:active {
	position:relative;
	top:1px;
}
*/
/* This css button was generated by css-button-generator.com */
</style>
    
	<script>

    </script>
	 <div class="table-holder">
     <form method="POST" action="<?php echo $_SERVER["REQUEST_URI"]; ?>">

	<b style="font-size:14px">Create Group </b><br>
    <input id="text1" type="text" name="T1" value="" style="height:28px;width:300px;border-color:lightgray">
    <button type="submit" class='css_btn_class' >CREATE</button><br>
    </form>
							
    <?php
		if(isset($_POST["T1"]))
		{
				$test=$_POST["T1"];
				if($test<>""){
    				$strSqlCommand  = "INSERT INTO `ggroup` (`GGroup_Name`) VALUES ('$test');";
					mysql_query($strSqlCommand);
				}
		}
	?>

    <?php
		$SQLcommand = "SELECT * FROM GGroup";
		//$num_rows = mysql_num_rows(mysql_query($SQLcommand));

		echo "<br>";
				
		$strSqlCommand1 = "SELECT * FROM GGroup";
		$result = mysql_query($strSqlCommand1);
		$count = 0;
      	
		if(isset($_POST['foo']))
        {
            $test = $_POST['foo'];

            $strSqlCommand1="DELETE FROM GGroup WHERE id='".$test."'";
            //echo "DELETE FROM GGroup WHERE GGroup_Name='".$test."'";

            mysql_query($strSqlCommand1);
            $strsqlCommand3="UPDATE  `incident` SET  `ggroup_id` =0 WHERE  `ggroup_id` =".$test;
            mysql_query($strsqlCommand3);
            echo "<meta content='0.00000000000000000001' http-equiv='Refresh'/>";
        }
		echo "<table class='table'>";
			echo "<thead>";
				echo "<tr>";
					echo "<th class='col-2' style='width:350px;padding-left:10px;'>Groups List</th>";
				echo "</tr>";
			echo "</thead>";
		echo "<tbody>";
		while ($row = mysql_fetch_array ($result)) {
			echo "<tr>";
			echo "<td style='border-style:solid;border-width:2px;border-color:darkgray;padding-left:15px;'>";
			echo "<form method='POST' action='group'>";
			//echo "<b>Group : </b>";
			echo "<input  type='text' style='border:0px;font-size:12px;font-weight: bold;width:350px' readonly='readonly' value='".$row['GGroup_Name']."'>";
			echo "<button type='submit' name='foo' value='".$row['id']."' class='css_btn_class' style='position: relative; right:-444px'>DELETE</button>";
			echo "</form>";
			echo "</td>";
			echo "</tr>";
			$count++;
		}
		echo "</tbody>";
		echo "</table>";

	?>

    </div>

</div>
